
package Views;

import Interfaces.Observable;
import Interfaces.Observer;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;


public class EffortDialog extends javax.swing.JDialog implements Observable{

    private JTable tabla;
    private Double c, e;
    private ArrayList<Observer> observers;

    /**
     * Creates new form Effort
     */
    public EffortDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        observers = new ArrayList<>();
        inicializarComponentes();
        
    }
    
    private void inicializarComponentes() {
        // configuramos los componentes
        tabla = this.jTable1;
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer(); //alinear al centro 
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
        for(int i = 0; i < tabla.getRowCount(); i++) {
            tabla.setValueAt(tabla.getValueAt(i, 2).toString().replace(',', '.'), i, 2);
            tabla.setValueAt(tabla.getValueAt(i, 3).toString().replace(',', '.'), i, 3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        titleLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "MF", "49,02", "0,736"},
                {"2", "MR", "78,88", "0,646"},
                {"3", "PC", "48,90", "0,661"},
                {"4", "Multi", "16,01", "0,865"},
                {"5", "3GL", "54,65", "0,717"},
                {"6", "4GL", "29,50", "0,758"},
                {"7", "GenAp", "68,11", "0,660"},
                {"8", "Mantenimiento", "52,58", "0,683"},
                {"9", "Nuevo", "39,05", "0,731"},
                {"10", "MF - 3GL", "65,37", "0,705"},
                {"11", "MF - 4GL ", "52,09", "0,640"},
                {"12", "MF - GenAp", "65,68", "0,692"},
                {"13", "MR - 3GL", "126,3", "0,565"},
                {"14", "MR - 4GL", "62,35", "0,694"},
                {"15", "PC -3GL", "60,46", "0,648"},
                {"16", "PC - 4GL", "36,48", "0,694"},
                {"17", "Multi - 3GL", "19,82", "0,666"},
                {"18", "Multi - 4GL", "6,49", "0,983"},
                {"19", "MF - 3GL - Mantenimeinto", "83,27", "0,650"}
            },
            new String [] {
                "", "Características", "C", "E"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setFocusable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        titleLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Colecciones de datos isbsg. Esfuerzo");

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = tabla.getSelectedRow();
        this.c = Double.valueOf(tabla.getValueAt(row, 2).toString());
        this.e = Double.valueOf(tabla.getValueAt(row, 3).toString());
        notifyObservers();
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    public Double getC() {
        return c;
    }

    public Double getE() {
        return e;
    }

    
    @Override
    public void addObserver(Observer o) {
        observers.add(o);
    }

    @Override
    public void notifyObservers() {
        for(int i=0;i<observers.size();i++){
            observers.get(i).actualizarEsfuerzo(c, e);
        }
    }
    
    
}
